name: TSR Notifier

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run TSR notifier
        env:
          DISCORD_TSR_WEBHOOK_URL: ${{ secrets.DISCORD_TSR_WEBHOOK_URL }}
        run: node tsr_notifier.js

      - name: Configure remote with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sent_posts.json need_to_check.json || true
          git commit -m "Update sent posts / need list" || echo "No changes to commit"
          git push
